"""empty message

Revision ID: 90fc8bac0ea3
Revises: e1c5933d1f1a
Create Date: 2026-09-08 23:27:25.190461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fc8bac0ea3'
down_revision: Union[str, None] = 'e1c5933d1f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_read_receipts_user_id'), table_name='read_receipts')
    op.drop_constraint(op.f('uq_read_receipt'), 'read_receipts', type_='unique')
    op.drop_column('read_receipts', 'id')
    op.execute("""
        ALTER TABLE read_receipts SET (
            fillfactor = 75,
            autovacuum_vacuum_scale_factor = 0.02,
            autovacuum_analyze_scale_factor = 0.05,
            autovacuum_vacuum_cost_delay = 0
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('read_receipts', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('uq_read_receipt'), 'read_receipts', ['chat_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_read_receipts_user_id'), 'read_receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###
